// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheWaterProject.Models;

#nullable disable

namespace TheWaterProject.Migrations
{
    [DbContext(typeof(WaterProjectContext))]
    partial class WaterProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("TheWaterProject.Models.Project", b =>
                {
                    b.Property<int>("projectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("programName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("projectImpact")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("projectInstallation")
                        .HasColumnType("TEXT");

                    b.Property<string>("projectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("projectPhase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("projectType")
                        .HasColumnType("TEXT");

                    b.HasKey("projectId");

                    b.ToTable("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
